services:
  client:
    image: oven/bun
    working_dir: /app
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: >
      sh -c "bun install &&
             bun run dev --host"
    depends_on:
      - db

  table-service:
    image: rust:latest
    working_dir: /usr/src/app
    ports:
      - "8080:8080"
    volumes:
      - ./server/table-service:/usr/src/app
      - cargo-cache:/usr/local/cargo/registry
      - target-cache:/usr/src/app/target
    environment:
      - DATABASE_URL=mysql://user:password@db:3306/db?ssl-mode=DISABLED
    command: cargo run --bin table-service
    depends_on:
      - db

  auth-service:
    image: rust:latest
    working_dir: /usr/src/app
    ports:
      - "8081:8080"
    volumes:
      - ./server/auth-service:/usr/src/app
      - cargo-cache:/usr/local/cargo/registry
      - target-cache:/usr/src/app/target
    environment:
      - DATABASE_URL=mysql://user:password@db:3306/db?ssl-mode=DISABLED
    command: cargo run --bin auth-service
    restart: always
    depends_on:
      - db

  row-service:
    image: rust:latest
    working_dir: /usr/src/app
    ports:
      - "8082:8080"
    volumes:
      - ./server/row-service:/usr/src/app
      - cargo-cache:/usr/local/cargo/registry
      - target-cache:/usr/src/app/target
    environment:
      - DATABASE_URL=mysql://user:password@db:3306/db?ssl-mode=DISABLED
    command: cargo run --bin row-service
    restart: always
    depends_on:
      - db

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: "db"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "password"
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - database:/var/lib/mysql

volumes:
  cargo-cache:
  target-cache:
  database:
