NAME:="server"
PORT:="8080"
NETWORK:="net"

net:
  docker network create {{NETWORK}}

build:
  docker build -t {{NAME}} .

run: stop
  docker run --network {{NETWORK}} --init -p {{PORT}}:{{PORT}} --rm --name {{NAME}} -v $(pwd)/database.db:/usr/src/app/database.db {{NAME}}

stop:
  if [ $(docker ps -q -f name={{NAME}} | wc -l) -gt 0 ]; then docker stop {{NAME}}; fi

clean: stop
  if [ $(docker ps -q -f name={{NAME}} | wc -l) -gt 0 ]; then docker rm {{NAME}}; fi
